repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: python-packages/aws-smithy-python/tests/unit/auth/aws4_testsuite/
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: linting
        name: lint
        description: runs make lint-py
        entry: 'make lint-py'
        language: system
        pass_filenames: false
