name: Lint code

on:
    push:
        branches: develop
    pull_request:
        branches: develop

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache0-py${{ matrix.python_version }}
        named-caches-hash: ${{ hashFiles('python-default.lock') }}
        base-branch: develop
        pants-ci-config: pants.ci.toml

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
