name: Lint code

on:
    push:
        branches: develop
    pull_request:
        branches: develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          # lint-v0 makes it easy to bust the cache if needed
          # just increase the integer to start with a fresh cache
          gha-cache-key: lint-v0
          named-caches-hash: ${{ hashFiles('python-default.lock') }}
          pants-ci-config: pants.ci.toml

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
