name: Type Check

on:
    push:
        branches: develop
    pull_request:
        branches: develop

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set up Python for type checking 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Initialize Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          # cache0 makes it easy to bust the cache if needed
          gha-cache-key: v0
          named-caches-hash: ${{ hashFiles('python-default.lock') }}
          pants-ci-config: pants.ci.toml

      - name: Run type checks
        run: |
          make check-py
