name: Type Check

on:
    push:
        branches: develop
    pull_request:
        branches: develop

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Initialize Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          # cache0 makes it easy to bust the cache if needed
          gha-cache-key: cache0-py${{ matrix.python_version }}
          named-caches-hash: ${{ hashFiles('python-default.lock') }}
          base-branch: develop
          pants-ci-config: pants.ci.toml

      - name: Run type checks
        run: |
          make check-py
